export const coworkings = [
  {
    id: 1,
    title: "Meeting-point",
    price: "от 500 ₽/день",
    description: "Офисы с дизайнерскими интерьерами и панорамными окнами, просторные и светлые места для индивидуальной работы, оборудованные всем необходимым, красивые коференц-залы и переговорные.",
    address: "ул. Охотный ряд, д.2",
    loadPercent: "75%",
    spaceType: ["openspace", "meeting-room", "office"],
    amenities: ["wifi", "coffee"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 6,
    cover: "/photos/coworkings/meeting-point/cover.jpg",
    gallery: ["/photos/coworkings/meeting-point/gallery/gallery-1.webp", "/photos/coworkings/meeting-point/gallery/gallery-2.webp", "/photos/coworkings/meeting-point/gallery/gallery-3.webp", "/photos/coworkings/meeting-point/gallery/gallery-4.webp", "/photos/coworkings/meeting-point/gallery/gallery-5.webp", "/photos/coworkings/meeting-point/gallery/gallery-6.webp",]
  },
  {
    id: 2,
    title: "Worknation",
    price: "от 700 ₽/день",
    description: "Рабочие места и смарт-офисы на 37 этаже башни «Федерация-Восток»",
    address: "наб. Пресненская, д.12",
    loadPercent: "65%",
    spaceType: ["openspace", "meeting-room", "office"],
    amenities: ["wifi", "printer", "parking"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 50,
    cover: "/photos/coworkings/worknation/cover.webp",
    gallery: ["/photos/coworkings/worknation/gallery/gallery-1.webp", "/photos/coworkings/worknation/gallery/gallery-2.webp", "/photos/coworkings/worknation/gallery/gallery-3.webp", "/photos/coworkings/worknation/gallery/gallery-4.webp",]
  },
  {
    id: 3,
    title: "SOK",
    description: "Каждый резидент может выбрать то, что ему необходимо для решения задач в конкретный день или на протяжении ближайших месяцев! Приходите работать где и когда вам удобно — а мы создадим для вас условия высокой продуктивности.",
    price: "от 600 ₽/день",
    address: "ул. Земляной Вал, д. 8",
    loadPercent: "30%",
    spaceType: ["openspace", "meeting-room"],
    amenities: ["wifi", "printer", "parking"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 20,
    cover: "/photos/coworkings/SOK/cover.webp",
    gallery: ["/photos/coworkings/SOK/gallery/img-1.webp", "/photos/coworkings/SOK/gallery/img-2.webp", "/photos/coworkings/SOK/gallery/img-3.webp", "/photos/coworkings/SOK/gallery/img-4.webp", "/photos/coworkings/SOK/gallery/img-5.webp", "/photos/coworkings/SOK/gallery/img-6.webp", "/photos/coworkings/SOK/gallery/img-7.webp", "/photos/coworkings/SOK/gallery/img-8.webp",]
  },
  {
    id: 4,
    title: "START HUB",
    price: "от 550 ₽/день",
    description: "START HUB — рабочее пространство в Москве, сочетающее готовые офисы, комфортные рабочие места и переговорные комнаты.",
    address: "Москва, ул. Большая Новодмитровская, дом 36, строение 12, вход 6",
    loadPercent: "45%",
    spaceType: ["openspace", "meeting-room"],
    amenities: ["wifi", "coffee"],
    rentTerm: "week",
    workSchedule: "24/7",
    seats: 30,
    cover: "/photos/coworkings/START_HUB/cover.webp",
    gallery: ["/photos/coworkings/START_HUB/gallery/img-1.webp", "/photos/coworkings/START_HUB/gallery/img-2.webp", "/photos/coworkings/START_HUB/gallery/img-3.webp", "/photos/coworkings/START_HUB/gallery/img-4.webp", "/photos/coworkings/START_HUB/gallery/img-5.webp", "/photos/coworkings/START_HUB/gallery/img-6.webp",]
  },

  {
    id: 6,
    title: "Smart Office",
    price: "от 650 ₽/день",
    description: "«Смарт Офис» - оригинальный формат рабочего пространства, организованный на территории бизнес-парка «К2», расположившегося на Калужском шоссе. «К2 Бизнес-парк» – это новый бизнес-центр класса «А» в Новой Москве, соответствующий высочайшим европейским стандартам, и по праву гордящийся тем, что первым в России завоевал наивысшую оценку по стандартам BREEAM.",
    address: "Калужское шоссе, 23-й километр, 14с3",
    loadPercent: "55%",
    spaceType: ["office"],
    amenities: ["wifi", "printer"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 10,
    cover: "/photos/coworkings/smart_office/cover.jpg",
    gallery: ["/photos/coworkings/smart_office/gallery/img-1.jpg", "/photos/coworkings/smart_office/gallery/img-2.jpg", "/photos/coworkings/smart_office/gallery/img-3.jpg", "/photos/coworkings/smart_office/gallery/img-4.jpg", "/photos/coworkings/smart_office/gallery/img-5.jpg", "/photos/coworkings/smart_office/gallery/img-6.jpg",]
  },
  {
    id: 7,
    title: "Workki Neo Geo",
    price: "от 720 ₽/день",
    description: "Workki Neo Geo – пространство для работы, отдыха и обмена опытом, раcполагающееся в дизайнерском бизнес-центре в активно развивающейся деловой части столицы. Коворкинг сочетает в себе эргономичное пространство, уникальный дизайн и комфортное месторасположение. Меблированные мини-офисы и рабочие места в опенспейс созданы, чтобы каждый участник бизнес-сообщества мог подобрать пространство как для индивидуальной работы, так и для работы своей компании. Продуманная планировка коворкинга позволяет резидентам общаться с коллегами и знакомиться с резидентами из других сфер, сохраняя приватность пространства в рабочее время. Локация, помимо кабинетов и опенспейс, содержит три обеденные зоны, кафе, ивент-зону и лекторий для съемок.",
    address: "улица Бутлерова, 17",
    loadPercent: "80%",
    spaceType: ["openspace", "beauty-workspace"],
    amenities: ["wifi", "coffee", "parking"],
    rentTerm: "week",
    workSchedule: "24/7",
    seats: 25,
    cover: "/photos/coworkings/workki/cover.jpg",
    gallery: ["/photos/coworkings/workki/gallery/img-1.jpg", "/photos/coworkings/workki/gallery/img-2.jpg", "/photos/coworkings/workki/gallery/img-3.webp", "/photos/coworkings/workki/gallery/img-4.webp", "/photos/coworkings/workki/gallery/img-5.webp",]
  },
  {
    id: 8,
    title: "Gravity Co-Working Space",
    description: "Gravity Co-Working — это просторное пространство в стиле лофт. Здесь всё располагает к продуктивной работе и способствует поиску правильных и эффективных решений. В распоряжении резидентов будет не только рабочее место, но и переговорные комнаты, кабинеты, конференц-залы и зал для проведения Хакатона. Gravity Co-Working также может похвастатся удачным месторасположением – 5 минут от метро Бауманская и бесплатной парковкой в центре города.",
    price: "от 400 ₽/день",
    address: "ул. Бауманская, д. 53, стр. 1",
    loadPercent: "20%",
    spaceType: ["meeting-room"],
    amenities: ["wifi"],
    rentTerm: "hour",
    workSchedule: "5/2",
    seats: 38,
    cover: "/photos/coworkings/gravity/cover.jpg",
    gallery: ["/photos/coworkings/gravity/gallery/img-1.jpg", "/photos/coworkings/gravity/gallery/img-2.jpg", "/photos/coworkings/gravity/gallery/img-3.jpg", "/photos/coworkings/gravity/gallery/img-4.jpg", "/photos/coworkings/gravity/gallery/img-5.jpg", "/photos/coworkings/gravity/gallery/img-6.jpg",]
  },
  {
    id: 9,
    title: "Atmosphere",
    price: "от 680 ₽/день",
    description: "Коворкинг «Атмосфера» занимает весь 6 этаж Торгово-развлекательного центра РИО «Ленинский», инфраструктура которого включает в себя вместительный и бесплатный внутренний паркинг, а также удобный подъезд, наличие большого числа ресторанов и кафе, удобных для деловых встреч и возможность посетить магазины или отдохнуть после работы.",
    address: "Москва, Ленинский проспект, 109",
    loadPercent: "60%",
    spaceType: ["office", "openspace"],
    amenities: ["wifi", "printer"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 40,
    cover: "/photos/coworkings/atmosphere/cover.webp",
    gallery: ["/photos/coworkings/atmosphere/gallery/img-1.webp", "/photos/coworkings/atmosphere/gallery/img-2.webp", "/photos/coworkings/atmosphere/gallery/img-3.webp", "/photos/coworkings/atmosphere/gallery/img-4.webp", "/photos/coworkings/atmosphere/gallery/img-5.webp", "/photos/coworkings/atmosphere/gallery/img-6.jpg",]

  },
  {
    id: 10,
    title: "Vibe",
    price: "от 900 ₽/день",
    description: "В коворкинге есть рабочие места для парикмахеров, визажистов, стилистов, барберов, мастеров маникюра и оборудованные кабинеты для педикюра, массажа, косметологических услуг — с раковиной и душевой кабиной. Плюс кабинет для барбера со студийным светом.",
    address: "Пятницкая улица, 62 с 7",
    loadPercent: "95%",
    spaceType: ["conference-room", "office"],
    amenities: ["wifi", "printer", "coffee", "parking"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 100,
    cover: "/photos/coworkings/vibe/cover.webp",
    gallery: ["/photos/coworkings/vibe/gallery/img-1.webp", "/photos/coworkings/vibe/gallery/img-2.webp", "/photos/coworkings/vibe/gallery/img-3.webp", "/photos/coworkings/vibe/gallery/img-4.webp", "/photos/coworkings/vibe/gallery/img-5.webp",]
  }
];