export const coworkings = [
  {
    id: 1,
    title: "Meeting-point",
    price: "от 500 ₽/день",
    address: "ул. Охотный ряд, д.2",
    loadPercent: "75%",
    spaceType: ["openspace","meeting-room", "office"],
    amenities: ["wifi", "coffee"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 6,
  },
  {
    id: 2,
    title: "Worknation",
    price: "от 700 ₽/день",
    address: "наб. Пресненская, д.12",
    loadPercent: "65%",
    spaceType: ["openspace", "meeting-room", "office"],
    amenities: ["wifi", "printer", "parking"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 50,
  },
  {
    id: 3,
    title: "Start Place",
    price: "от 600 ₽/день",
    address: "ул. Тверская, д.7",
    loadPercent: "30%",
    spaceType: ["openspace"],
    amenities: ["wifi"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 20,
  },
  {
    id: 4,
    title: "Open Space Hub",
    price: "от 550 ₽/день",
    address: "ул. Бауманская, д.11",
    loadPercent: "45%",
    spaceType: ["openspace", "meeting-room"],
    amenities: ["wifi", "coffee"],
    rentTerm: "week",
    workSchedule: "24/7",
    seats: 30,
  },
  {
    id: 5,
    title: "Creative Point",
    price: "от 800 ₽/день",
    address: "Ленинградский проспект, д.15",
    loadPercent: "90%",
    spaceType: ["office", "conference-room"],
    amenities: ["wifi", "printer", "coffee"],
    rentTerm: "month",
    workSchedule: "5/2",
    seats: 15,
  },
  {
    id: 6,
    title: "Smart Office",
    price: "от 650 ₽/день",
    address: "ул. Пятницкая, д.3",
    loadPercent: "55%",
    spaceType: ["office"],
    amenities: ["wifi", "printer"],
    rentTerm: "day",
    workSchedule: "5/2",
    seats: 10,
  },
  {
    id: 7,
    title: "Loft Workspace",
    price: "от 720 ₽/день",
    address: "ул. Большая Дмитровка, д.9",
    loadPercent: "80%",
    spaceType: ["openspace", "beauty-workspace"],
    amenities: ["wifi", "coffee", "parking"],
    rentTerm: "week",
    workSchedule: "24/7",
    seats: 25,
  },
  {
    id: 8,
    title: "Focus Room",
    price: "от 400 ₽/день",
    address: "ул. Арбат, д.25",
    loadPercent: "20%",
    spaceType: ["meeting-room"],
    amenities: ["wifi"],
    rentTerm: "hour",
    workSchedule: "5/2",
    seats: 4,
  },
  {
    id: 9,
    title: "Urban Office",
    price: "от 680 ₽/день",
    address: "Кутузовский проспект, д.45",
    loadPercent: "60%",
    spaceType: ["office", "openspace"],
    amenities: ["wifi", "printer"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 40,
  },
  {
    id: 10,
    title: "Tech Hub",
    price: "от 900 ₽/день",
    address: "Сколково, ул. Новая, д.100",
    loadPercent: "95%",
    spaceType: ["conference-room", "office"],
    amenities: ["wifi", "printer", "coffee", "parking"],
    rentTerm: "month",
    workSchedule: "24/7",
    seats: 100,
  }
];